name: build and deploy to dockerhub

on:
  push:
   branches: none #[ master ]
  pull_request:
    branches: none #[ master ]
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "gouravsaini" --password-stdin
        docker image build -t ${{ secrets.IMAGE_NAME }}:latest --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe --build-arg=FRAPPE_BRANCH=version-14 --build-arg=PYTHON_VERSION=3.10.5   --build-arg=NODE_VERSION=16.18.0   --build-arg=APPS_JSON_BASE64=${{ secrets.BASE_64 }} .
        docker push ${{ secrets.IMAGE_NAME }}:latest
