name: CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["build and deploy to dockerhub"]
    types:
      - completed
        
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            whoami
            ls -al
