name: CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["build and deploy to dockerhub"]
    types:
      - completed
  workflow_dispatch:
        
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSHKEYPASSWORD }}
        port: 22
        script: |
            docker compose -f ${{ secrets.DOCKER_FILE_PATH }} down
            docker rm --force container $(docker container ls -qa )
            docker pull ${{ secrets.IMAGE_NAME }}:latest
            docker compose -f ${{ secrets.DOCKER_FILE_PATH }} up -d
            
